
###################################################################
# User 

mutation CreateUserDisplayName(
    $displayNameText: String!
) @auth(level: USER) @transaction {

    # Step 1: Check if display name already exists
    # an insert will also be prevented if the user is already hogging 5 displayNames
    query
    @check( expr: "response.query.displayNamesForUser.size() < 6 && response.query.displayNamesMatchingText.size() == 0",
            message: "That display name already exists, or you have already have too many display names.  Please choose another."
    ) {
        displayNamesForUser: userDisplayNames(
            where: { createUser: { id: { eq: "auth.uid" } } }
        ) {
            text
        }

        displayNamesMatchingText: userDisplayNames(
            where: { text: { eq: $displayNameText } }
        ) {
            text
        }
    }

    # Step 2: Insert new display name
    userDisplayName_insert(
        data: {
            text: $displayNameText
            createUserId_expr: "auth.uid"
        }
    )
}

mutation CreateUserAccount(
    $createDeviceIdentifierstamp: String!
    $createDeviceTimestamp: String!
    $displayNameText: String!
    $photoUrl: String!
) @auth(level: USER) {
    userAccount_insert(
        data: {
            id_expr: "auth.uid"
            createDeviceIdentifierstamp: $createDeviceIdentifierstamp
            createDeviceTimestamp: $createDeviceTimestamp
            displayNameText: $displayNameText
            photoUrl: $photoUrl
        }
    )
}

mutation UpdateUserAccountDisplayName(
    $updateDeviceIdentifierstamp: String!
    $updateDeviceTimestamp: String! 
    $displayNameText: String!
) @auth(level: USER) @transaction {

    # Step 1: make sure the user already 'owns' this Display Name
    query @check(
        expr: "response.query.name.createUser.id == auth.uid"
        message: "You don’t own this display name. Please pick another."
    ) {
        name: userDisplayName(key: { text: $displayNameText }) {
            text
            createUser { id }
        }
    }

    # Step 2: Update Display Name, to keep track of the set timestamp
    userDisplayName_update(
        key: { text: $displayNameText }
        data: {
            setTimestamp_expr: "request.time"
            setDeviceIdentifierstamp: $updateDeviceIdentifierstamp
            setDeviceTimestamp: $updateDeviceTimestamp
        }   
    )

    # Step 3: Update User Account
    userAccount_update(id_expr: "auth.uid",
        data: {
            updateTimestamp_expr: "request.time"
            updateDeviceIdentifierstamp: $updateDeviceIdentifierstamp
            updateDeviceTimestamp: $updateDeviceIdentifierstamp
            displayNameText: $displayNameText
        }
    )
}

mutation UpdateUserAccountProfile(
    $updateDeviceIdentifierstamp: String!
    $updateDeviceTimestamp: String!
    $photoUrl: String!
    # add other fields as needed
) @auth(level: USER) {
    userAccount_update(id_expr: "auth.uid"
        data: {
            updateTimestamp_expr: "request.time"
            updateDeviceIdentifierstamp: $updateDeviceIdentifierstamp
            updateDeviceTimestamp: $updateDeviceTimestamp
            photoUrl: $photoUrl
            # add other fields as needed
        }
    )
}


###################################################################
# User Demographic Profile
# A User Demographic Profile for a particular user can be changed
# by inserting a new row.

mutation CreateUserDemographicProfile(
    $createDeviceIdentifierstamp: String!
    $createDeviceTimestamp: String!
    $gender:   DemographicsGender_Key!
    $generation: DemographicsGeneration_Key!
    $region:   DemographicsRegion_Key!
    $urbanicity: DemographicsUrbanicity_Key!
    $political: DemographicsPolitical_Key!
) @auth(level: USER) {
  userDemographicProfile_insert(
    data: {
        createUserId_expr: "auth.uid"
        createDeviceIdentifierstamp: $createDeviceIdentifierstamp
        createDeviceTimestamp: $createDeviceTimestamp
        gender: $gender
        generation: $generation
        region: $region
        urbanicity: $urbanicity
        political: $political
    }
  )
}


###################################################################
# Cross-User Relationships
# User Relationships can be changed by inserting a new row.

mutation CreateUserAssociation(
    $associateUserId: String!
    $createDeviceIdentifierstamp: String!
    $createDeviceTimestamp: String!
    $follow: Boolean
    $block: Boolean
    $autoSharePrivateContent: Boolean
#) @auth(level: USER_EMAIL_VERIFIED) {
) @auth(level: USER) {
  userAssociation_insert(
    data: {
        createUserId_expr: "auth.uid"
        associateUserId: $associateUserId
        createDeviceIdentifierstamp: $createDeviceIdentifierstamp
        createDeviceTimestamp: $createDeviceTimestamp
        follow: $follow
        block: $block
        autoSharePrivateContent: $autoSharePrivateContent
    }
  )
}


###################################################################
# User Comments, User Messages

mutation CreatePublicComment(
    $toUserId: String!
    $toUserDisplayNameText: String!
    $createDeviceIdentifierstamp: String!
    $createDeviceTimestamp: String!
    $title: String!
    $content: String!
#) @auth(level: USER_EMAIL_VERIFIED) {
) @auth(level: USER) {
    publicComment_insert(
        data: {
            createUserId_expr: "auth.uid"
            toUserId: $toUserId
            toUserDisplayNameText: $toUserDisplayNameText
            createDeviceIdentifierstamp: $createDeviceIdentifierstamp
            createDeviceTimestamp: $createDeviceTimestamp
            title: $title
            content: $content
        }
    )
}

mutation CreatePrivateMessage(
    $toUserId: String!
    $toUserDisplayNameText: String!
    $createDeviceIdentifierstamp: String!
    $createDeviceTimestamp: String!
    $title: String!
    $content: String!
#) @auth(level: USER_EMAIL_VERIFIED) {
) @auth(level: USER) {
    privateMessage_insert(
        data: {
            createUserId_expr: "auth.uid"
            toUserId: $toUserId
            toUserDisplayNameText: $toUserDisplayNameText
            createDeviceIdentifierstamp: $createDeviceIdentifierstamp
            createDeviceTimestamp: $createDeviceTimestamp
            title: $title
            content: $content
        }
    )
}

mutation CreatePublicCommentReference(
    $publicCommentId: UUID!
    $referenceId: UUID!
#) @auth(level: USER_EMAIL_VERIFIED) {
) @auth(level: USER) {
    publicCommentReference_insert(
        data: {
            publicCommentId: $publicCommentId
            referenceId: $referenceId
            createUserId_expr: "auth.uid"
        }
    )
}

mutation CreatePrivateMessageReference(
    $privateMessageId: UUID!
    $referenceId: UUID!
#) @auth(level: USER_EMAIL_VERIFIED) {
) @auth(level: USER) {
    privateMessageReference_insert(
        data: {
            privateMessageId: $privateMessageId
            referenceId: $referenceId
            createUserId_expr: "auth.uid"
        }
    )
}

mutation CreatePrivateMessageStatus(
    $privateMessageId: UUID!
    $status: String!
#) @auth(level: USER_EMAIL_VERIFIED) {
) @auth(level: USER) {
    privateMessageStatus_insert(
        data: {
            privateMessageId: $privateMessageId
            createUserId_expr: "auth.uid"
            status: $status
        }
    )
}
