
###################################################################
# User 

type UserAccount @table(key: ["id"]) {
    id: String! @default(expr: "auth.uid")
    createTimestamp: Timestamp! @default(expr: "request.time")
    createDeviceIdentifierstamp: String!
    createDeviceTimestamp: String!
    updateDeviceIdentifierstamp: String!
    updateDeviceTimestamp: String!
    displayNameText: String!
    photoUrl: String!
}

type UserDisplayName @table(key: ["text"]) {
    text: String! @unique
    createUser: UserAccount!
    createTimestamp: Timestamp! @default(expr: "request.time")
    createDeviceIdentifierstamp: String!
    createDeviceTimestamp: String!
}


###################################################################
# User Demographic Profile
# A User Demographic Profile for a particular user can be changed
# by inserting a new row.

type UserDemographicProfile @table {
    id: UUID! @default(expr: "uuidV4()")
    createUser: UserAccount!
    createTimestamp: Timestamp! @default(expr: "request.time")
    createDeviceIdentifierstamp: String!
    createDeviceTimestamp: String!
    gender: DemographicsGender!
    generation: DemographicsGeneration!
    region: DemographicsRegion!
    urbanicity: DemographicsUrbanicity!
    political: DemographicsPolitical!
}


###################################################################
# Cross-User Relationships
# User Relationships can be changed by inserting a new row.

type UserAssociation @table {
    id: UUID! @default(expr: "uuidV4()")
    createUser: UserAccount!
    associateUserId: String! @index
    associateUserDisplayNameText: String!
    createTimestamp: Timestamp! @default(expr: "request.time")
    createDeviceIdentifierstamp: String!
    createDeviceTimestamp: String!
    follow: Boolean! @default(value: false)
    block: Boolean! @default(value: false)
    autoSharePrivateContent: Boolean! @default(value: false)
}


###################################################################
# User Comments, User Messages

type PublicComment @table {
    id: UUID! @default(expr: "uuidV4()")
    createUser: UserAccount!
    toUserId: String
    toUserDisplayNameText: String
    createTimestamp: Timestamp! @default(expr: "request.time")
    createDeviceIdentifierstamp: String!
    createDeviceTimestamp: String!
    title: String!
    content: String!
}


type PrivateMessage @table {
    id: UUID! @default(expr: "uuidV4()")
    createUser: UserAccount!
    toUserId: String
    toUserDisplayNameText: String
    createTimestamp: Timestamp! @default(expr: "request.time")
    createDeviceIdentifierstamp: String!
    createDeviceTimestamp: String!
    title: String!
    content: String!
}

type PublicCommentReference @table(
    key: ["publicComment", "referenceId"]
) {
    publicComment: PublicComment!
    referenceId: UUID! @index
    createUserId: String! @default(expr: "auth.uid")
    createTimestamp: Timestamp! @default(expr: "request.time")
}

type PrivateMessageReference @table(
    key: ["privateMessage", "referenceId"]
) {
    privateMessage: PrivateMessage!
    referenceId: UUID! @index
    createUserId: String! @default(expr: "auth.uid")
    createTimestamp: Timestamp! @default(expr: "request.time")
}

type PrivateMessageStatus @table {
    id: UUID! @default(expr: "uuidV4()")
    privateMessage: PrivateMessage!
    createUser: UserAccount!
    createTimestamp: Timestamp! @default(expr: "request.time")
    status: String!     # expected values "draft", "sent", "read", "archived", "deleted"
}


###################################################################
# Demographic Values

type DemographicsGender @table(
    key: ["key"]
) {
    key: String! @unique
    name: String!
    description: String!
    photoUrl: String
}

type DemographicsGeneration @table(
    key: ["key"]
) {
    key: String!
    name: String!
    description: String!
    birthYearStart: Int!
    birthYearEnd: Int!
    photoUrl: String
}

type DemographicsRegion @table(
    key: ["key"]
) {
    key: String!
    name: String!
    description: String!
    photoUrl: String
}

type DemographicsUrbanicity @table(
    key: ["key"]
) {
    key: String!
    name: String!
    description: String!
    photoUrl: String
}

type DemographicsPolitical @table(
    key: ["key"]
) {
    key: String!
    name: String!
    description: String!
    photoUrl: String
}