
###################################################################
# User Profile
# User Profile for a particular user can be changed
# by inserting a new row.

type UserProfile @table {
    id: UUID! @default(expr: "uuidV4()")
    userId: String! @index
    createTimestamp: Timestamp! @default(expr: "request.time")
    createDeviceStamp: String!
    displayName: String!
    photoUrl: String
}


###################################################################
# User Demographic Profile
# User Demographic Profile for a particular user can be changed
# by inserting a new row.

type UserDemographicProfile @table {
    id: UUID! @default(expr: "uuidV4()")
    userId: String! @index
    createTimestamp: Timestamp! @default(expr: "request.time")
    gender: DemographicsGender!
    generation: DemographicsGeneration!
    region: DemographicsRegion!
    urbanicity: DemographicsUrbanicity!
    political: DemographicsPolitical!
}

type DemographicsGender @table(
    key: ["key"]
) {
    key: String! @unique
    name: String!
    description: String!
    photoUrl: String
}

type DemographicsGeneration @table(
    key: ["key"]
) {
    key: String!
    name: String!
    description: String!
    birthYearStart: Int!
    birthYearEnd: Int!
    photoUrl: String
}

type DemographicsRegion @table(
    key: ["key"]
) {
    key: String!
    name: String!
    description: String!
    photoUrl: String
}

type DemographicsUrbanicity @table(
    key: ["key"]
) {
    key: String!
    name: String!
    description: String!
    photoUrl: String
}

type DemographicsPolitical @table(
    key: ["key"]
) {
    key: String!
    name: String!
    description: String!
    photoUrl: String
}

###################################################################
# Cross-User Relationships
# User Relationships can be changed by inserting a new row.

type UserAssociation @table {
    id: UUID! @default(expr: "uuidV4()")
    userId: String! @index
    createTimestamp: Timestamp! @default(expr: "request.time")
    associateUserId: String! @index
    autoSharePrivateTopics: Boolean
    follow: Boolean
    block: Boolean
}


###################################################################
# User Messages and Comments 

type PublicComment @table {
    id: UUID! @default(expr: "uuidV4()")
    createTimestamp: Timestamp! @default(expr: "request.time")
    createUserId: String! @index
    status: String!     # expected values "sent"
    title: String!
    content: String!
}

type PublicCommentReference @table(
    key: ["publicComment", "referenceId"]
) {
    publicComment: PublicComment!
    referenceId: UUID!
    createTimestamp: Timestamp! @default(expr: "request.time")
    createUserId: String! @index
}

type PrivateMessage @table {
    id: UUID! @default(expr: "uuidV4()")
    createTimestamp: Timestamp! @default(expr: "request.time")
    fromUserId: String! @index
    toUserId: String! @index
    updateUserId: String!
    status: String!     # expected values "sent", "read", "deleted"
    title: String!
    content: String!
}

type PrivateMessageReference @table(
    key: ["privateMessage", "referenceId"]
) {
    privateMessage: PrivateMessage!
    referenceId: UUID!
    createTimestamp: Timestamp! @default(expr: "request.time")
    createUserId: String! @index
}
